# Generated by Django 4.2.4 on 2023-09-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garagem", "0002_veiculo_foto"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelo",
            name="nome",
            field=models.CharField(default="hilux", max_length=200),
            preserve_default=False,
        ),
    ]
